SELECT DBMS_XDB_CONFIG.GETHTTPPORT()  AS HTTP_PORT,
       DBMS_XDB_CONFIG.GETHTTPSPORT() AS HTTPS_PORT
FROM dual;
BEGIN
  DBMS_XDB_CONFIG.SETHTTPPORT(8080);
  DBMS_XDB_CONFIG.SETHTTPSPORT(8443);
END;
/
SHUTDOWN IMMEDIATE;
STARTUP;
